### ISSUE TITLE
Investigate the "Init()" function in the evaluation_page html file

### ISSUE THREAD

**Issue by zhouhuan200010pm** [Lunatic-Labs/rubricapp#162]
The "Init()" function down in the Javascript part of templates/evaluation_page.html seems outdated. For example the function does things that seem to already be handled by the HTML file.

**Comment by sah0017** [comment]
@mr21Awesomeness This was raised as an issue by the legacy team.  Do the changes that you've made/are making fix this issue?

**Comment by mr21Awesomeness** [comment]
@sah0017 The changes that I made do not fix this issue.

**Comment by mr21Awesomeness** [comment]
I took a look at the code and broke up the init() function into 6 main parts.
Part 1, lines 1223-1230, Selects all of the checkboxes on the page and clicks the checkboxes twice if they are true.
Function: Toggle checkboxes on the page twice.
Problem: Double clicking a checkbox if it is true does nothing.
Solution: Remove lines 1223-1230 that do nothing or remove line 1228 that clicks the checkbox a second time so that all the checkboxes that are true are set to false when the page is loaded.
Part 2, lines 1231-1238, Selects all of the radios and labels. Looks at all the radios, if radio is checked, then the corresponding label is clicked.
Function: To set a checkbox false if the checkbox is true.
Problem: Do not understand the need to set the checkboxes false if they are true.
Solution: Determine if we want to set all checkboxes that are true to false when the page is loaded.
Part 3, lines 1239-1247, Selects all of the panel headings, bodies, and footers and sets their background color to a linear-gradient.
Function: To initialize the panel headings, bodies, and footers to the linear-gradient. 
Problem: Setting the panel headings, bodies, and footers background to a linear gradient can be done with css.
Solution: Remove lines 1239-1247 and create css to set the background color to all the panel headings, bodies, and footers to the linear-gradient in the “bootstrap.css” file.
Part 4, lines 1248-1252, Selects the switch groups button and clicks on it. Scrolls to the top left. Selects the list of groups stored in the database and prints it to the console.
Function: Initializes the page with the switch groups tab opened and scrolls to the top left. Then prints the stored list of groups to the console.
Problem: Do not know why the page is scrolled to the top left if this is done by default. Do not know why the list of groups is printed to the console.
Solution: Remove line 1250 to scroll the page to the top left and remove line 1252 to print the list of groups to the console.
Part 5, lines 1253-1263, Selects all of the group links and looks at each one. If a group link’s innerHTML matches the stored value in the database, then the group link’s background color is set to nothing.
Function: Set the background color of groups that exist in the database to nothing.
Problem: Do not know why the groups that are stored in the database are set to have no background color.
Solution: Determine if we want corresponding stored groups to have a background color of nothing when page is loaded.
Part 6, lines 1264-1266, Calls the updateLastEditTime() function, selects the element as an id of “logo” to be focused.
Function: Update the time the evaluation is edited to the current time. Set focus on the element with the id of “logo”.
Problem: There is no element on the page with the id of “logo”.
Solution: Remove lines 1265 and 1266 that select the non-existing element and focuses on the non-existing element.

**Comment by mr21Awesomeness** [comment]
After further inspection, parts 1, 2, and some of 4 should not be removed.
Part 1 toggles all the saved checked boxes to update the counter for currently checked boxes when the page is loaded. With the current logic, the function to count all the currently checked boxes only gets run when the checkboxes are toggles. 
Part 2 toggles the saved rating to update the currently selected rating when the page is loaded. With the current logic, the function to display the currently selected rating only gets run when the rating is clicked.
Part 4 line 1250 scrolls the window to the top left. By default the page does not scroll the the top when reloaded, only when the browser is redirected to the evaluation page.
